### ISSUE TITLE
User can choose between different car models.

### ISSUE THREAD

**Issue by byu014** [byu014/driving-game#11]
## 💰 Motivation

The user needs to be able to change to different cars.

## 📐 Plan

Provide a menu of selectable cars

## ✅ Task List

- [x] create object that contains all car options
- [x] create HTML for buttons to represent each car
- [x] add event listener to listen for clicks on button containing div to switch cars based on button clicked
