### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by byu014** [byu014/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## Example

![user can start their car](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/demos/driving-game/user-can-start-their-car.gif)

## ✅ Task List

- [x] Add a location to your data model to hold the car's x and y coordinates on the page.
- [x] Use absolute positioning for your image.
- [x] Use the style property of element objects to change your car's top and left box offset styles.
- [x] Move your car every 16 milliseconds for a smooth movement.
- [x] The car doesn't have to change directions yet, that's a different feature.
